INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '提现申请', '2', 'icon-qian', '/balance/withdrawal', 'balanceWithdrawal', 'userBalance', ',userBalance,balanceWithdrawal,', '/balance/withdrawal', NULL, '0', '1', NULL, '1', '2025-04-22 12:19:23', '2025-04-22 12:19:23');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '只浏览数据', '6', '', '', 'balanceWithdrawalGetList', 'balanceWithdrawal', ',userBalance,balanceWithdrawal,balanceWithdrawalGetList,', '', NULL, '0', '1', NULL, '1', '2025-04-22 12:19:23', '2025-04-22 12:19:23');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '查看详情', '6', '', '', 'balanceWithdrawalInfo', 'balanceWithdrawal', ',userBalance,balanceWithdrawal,balanceWithdrawalInfo,', '', NULL, '3', '1', NULL, '1', '2025-04-22 12:19:23', '2025-04-22 12:19:23');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '审核打款操作', '6', '', '', 'balanceWithdrawalUpdateStatus', 'balanceWithdrawal', ',userBalance,balanceWithdrawal,balanceWithdrawalUpdateStatus,', '', NULL, '6', '1', NULL, '1', '2025-04-22 12:19:23', '2025-04-22 15:07:37');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '导出数据', '6', '', '', 'balanceWithdrawalExportData', 'balanceWithdrawal', ',userBalance,balanceWithdrawal,balanceWithdrawalExportData,', '', NULL, '7', '1', NULL, '1', '2025-04-22 12:19:23', '2025-04-22 12:19:23');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '用户余额', '1', 'icon-money-new', '', 'userBalance', NULL, ',userBalance,', '', NULL, '0', '1', NULL, '1', '2024-12-09 16:44:00', '2024-12-09 16:44:00');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '余额管理', '2', 'icon-money-new', '/balance', 'balance', 'userBalance', ',userBalance,balance,', '/balance', NULL, '0', '1', NULL, '1', '2024-12-09 16:44:41', '2024-12-09 16:44:41');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '只浏览数据', '6', '', '', 'balanceGetList', 'balance', ',userBalance,balance,balanceGetList,', '', NULL, '0', '1', NULL, '1', '2024-12-09 16:44:41', '2024-12-09 16:44:41');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '导出数据', '6', '', '', 'balanceExportData', 'balance', ',userBalance,balance,balanceExportData,', '', NULL, '7', '1', NULL, '1', '2024-12-09 16:44:41', '2024-12-09 16:44:41');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '余额明细', '2', 'icon-wenzhang2', '/balance/details', 'balanceDetails', 'userBalance', ',userBalance,balanceDetails,', '/balance/details', NULL, '1', '1', NULL, '1', '2024-12-09 16:45:34', '2024-12-09 16:45:34');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '只浏览数据', '6', '', '', 'balanceDetailsGetList', 'balanceDetails', ',userBalance,balanceDetails,balanceDetailsGetList,', '', NULL, '0', '1', NULL, '1', '2024-12-09 16:45:34', '2024-12-09 16:45:34');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '导出数据', '6', '', '', 'balanceDetailsExportData', 'balanceDetails', ',userBalance,balanceDetails,balanceDetailsExportData,', '', NULL, '7', '1', NULL, '1', '2024-12-09 16:45:34', '2024-12-09 16:45:34');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '变更用户余额', '6', '', '', 'updateBalance', 'balance', ',userBalance,balance,updateBalance,', '', NULL, '1', '1', NULL, '1', '2024-12-09 16:57:46', '2024-12-09 16:57:52');
INSERT INTO `superadminx_preview`.`sa_admin_menu` (`title`, `type`, `icon`, `path`, `name`, `pid_name`, `pid_name_path`, `component_path`, `url`, `sort`, `hidden`, `desc`, `is_params`, `create_time`, `update_time`) VALUES ( '提现设置', '7', 'icon-peizhi1', '/config/balance_withdraw_config', 'config_balance_withdraw_config', 'configManage', ',configManage,config_balance_withdraw_config,', '', NULL, '0', '1', '', '1', '2025-04-22 14:29:49', '2025-04-22 16:13:03');

INSERT INTO `superadminx_preview`.`sa_config` (`type`, `list_number`, `name`, `title`, `description`, `fields_config`, `content`, `sort`, `create_time`, `update_time`) VALUES ('form', '0', 'balance_withdraw_config', '提现设置', '', '[{\"id\":1745303299419,\"dataIndex\":\"min\",\"valueType\":\"digit\",\"valueTypeTitle\":\"数字\",\"name\":\"min\",\"title\":\"最小提现金额\",\"formItemProps\":{\"rules\":[{\"required\":true,\"message\":\"必填\"}],\"style\":{\"width\":\"100%\"}},\"fieldProps\":{\"style\":{\"width\":\"100%\"},\"min\":0.01},\"fields\":[],\"updateFields\":{\"name\":\"min\",\"title\":\"最小提现金额\",\"required\":2,\"min\":0.01}},{\"id\":1745303329490,\"dataIndex\":\"shouxufei_bili\",\"valueType\":\"digit\",\"valueTypeTitle\":\"数字\",\"name\":\"shouxufei_bili\",\"title\":\"提现手续费\",\"formItemProps\":{\"rules\":[{\"required\":true,\"message\":\"必填\"}],\"style\":{\"width\":\"100%\"},\"extra\":\"是百分比，输入1则代表将收取1%的手续费\"},\"fieldProps\":{\"style\":{\"width\":\"100%\"},\"addonAfter\":\"%\",\"min\":0,\"max\":99.9},\"fields\":[],\"updateFields\":{\"name\":\"shouxufei_bili\",\"title\":\"提现手续费\",\"extra\":\"是百分比，输入1则代表将收取1%的手续费\",\"required\":2,\"min\":0,\"max\":99.9,\"addonAfter\":\"%\"}},{\"id\":1745309563339,\"dataIndex\":\"bank_list\",\"valueType\":\"textarea\",\"valueTypeTitle\":\"多行文本\",\"name\":\"bank_list\",\"title\":\"提现银行\",\"formItemProps\":{\"rules\":[{\"required\":true,\"message\":\"必填\"}],\"style\":{\"width\":\"100%\"},\"extra\":\"每行输入一个银行\"},\"fieldProps\":{\"style\":{\"width\":\"100%\"}},\"fields\":[],\"updateFields\":{\"name\":\"bank_list\",\"title\":\"提现银行\",\"extra\":\"每行输入一个银行\",\"required\":2}}]', '{\"min\":100,\"shouxufei_bili\":2,\"bank_list\":\"工商银行\\n建设银行\\n招商银行\\n重庆农商行\"}', '0', '2025-04-22 14:29:49', '2025-04-22 16:13:25');
